[package]
name = "keepass-ffi"
version = "0.0.1"
edition = "2021"
description = "Unofficial & unaffiliated keepass-rs FFI wrapper"
repository = "https://github.com/ManyMath/keepass-ffi"
license = "MIT"

[lib]
name = "keepass"
path = "src/lib.rs"
crate-type = ["cdylib", "staticlib"]

[dependencies]
